# Generated by Django 3.1.12 on 2024-04-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='etapa',
            field=models.CharField(choices=[('CRIADO', 'Criado'), ('ENVIADO', 'Enviado'), ('CONFIRMADO', 'Confirmado'), ('FATURADO', 'Faturado')], default='CONFIRMAR', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='representante',
            name='nivel',
            field=models.CharField(choices=[('CONFIRMAR', 'Confirmar'), ('JUNIOR', 'Junior'), ('PLENO', 'Pleno'), ('SENIOR', 'Senior'), ('CONFIRMADO', 'Confirmado')], default='CONFIRMAR', max_length=20),
            preserve_default=False,
        ),
    ]
