# Generated by Django 3.1.12 on 2024-05-18 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rastreio',
            options={'permissions': [('can_add_track', 'Pode atualizar status do rastreamento')]},
        ),
    ]
