# Generated by Django 3.1.12 on 2024-05-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_auto_20240517_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rastreio',
            options={'permissions': [('can_track', 'Pode rastrear um pedido'), ('can_add_track', 'Pode atualizar status do rastreamento')]},
        ),
    ]
