# Generated by Django 3.1.12 on 2024-04-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_auto_20240421_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'permissions': [('can_list', 'Pode listar os pedidos'), ('can_create', 'Pode criar um novo pedido'), ('can_update', 'Pode atualizar um pedido existente'), ('can_detail', 'Pode visualizar os detalhes de um pedido'), ('can_send', 'Pode enviar o pedido'), ('can_confirm', 'Pode confirmar o envio de um pedido')]},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='etapa',
            field=models.CharField(choices=[('criado', 'Criado'), ('enviado', 'Enviado'), ('confirmado', 'Confirmado'), ('faturado', 'Faturado'), ('cancelado', 'Cancelado')], default='criado', max_length=20),
        ),
    ]
