services:
  mongo:
    image: mongo:7.0.5
    restart: always
    container_name: mongo_7_0_5
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/etc/mongo
      - mongo_data:/data/db

volumes:
  mongo_data: {}